module.exports = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consequat nulla tempus felis consectetur ultricies. Cras commodo felis non eleifend rhoncus. Integer egestas non lacus molestie condimentum. Ut vitae libero nisi. Sed quis lacinia metus, ut lacinia metus. Sed dignissim quam nec erat semper, et sodales leo interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis sodales erat, in imperdiet turpis. Mauris porta tempus nulla, eget ornare urna interdum eget.",

  "Curabitur a iaculis justo. Vestibulum eget neque molestie, eleifend justo sed, fermentum ante. Sed gravida erat ac nisl tempor volutpat. Aliquam et euismod sem. Phasellus in lorem commodo, mattis ligula vitae, auctor dolor. Integer fermentum id turpis sit amet tempor. Vivamus pretium, dui ac tempus convallis, turpis lorem suscipit ex, et sollicitudin nulla nisi nec odio. Nam congue erat sit amet lectus consequat, eget sodales est tempus. Sed blandit ac libero sed rutrum. Fusce eu nisi vitae nisl eleifend aliquet. Donec feugiat quis velit eget pellentesque. Donec elementum fermentum metus, et vulputate arcu iaculis ac. Etiam non rutrum est.",

  "Proin finibus ipsum in justo viverra, vel iaculis velit viverra. Nullam tempus placerat eleifend. Sed pellentesque est sit amet turpis volutpat egestas. Pellentesque fringilla mattis nibh, in condimentum risus laoreet in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus vestibulum placerat neque, non mollis arcu placerat vitae. Praesent tristique, elit ac gravida pellentesque, elit diam efficitur orci, sed porttitor magna lorem ut enim. Nunc laoreet dui eget nulla faucibus gravida. Aenean quis convallis justo. Etiam egestas neque purus, sollicitudin blandit nunc ultricies eleifend. Fusce aliquam, diam et consequat venenatis, felis nulla venenatis quam, sed sagittis eros orci nec neque. Vivamus non urna faucibus, imperdiet felis in, feugiat nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas volutpat molestie risus vitae eleifend. Donec vestibulum velit vitae tempor maximus.",

  "Nulla massa tortor, rhoncus vel porttitor a, aliquet ut libero. Vivamus id euismod nunc. Nunc erat arcu, fermentum non tortor et, consequat maximus elit. Nullam vehicula, sapien sed feugiat semper, purus elit sollicitudin velit, vel dapibus leo libero at velit. Mauris semper tincidunt massa, quis suscipit lorem rutrum quis. In ac ex est. Duis scelerisque varius sem eget blandit. Suspendisse in consectetur odio, quis rhoncus lacus. Vivamus et egestas magna. Proin eget ligula in neque elementum posuere. Aenean orci nulla, placerat ac mattis a, consectetur nec nulla.",

  "Pellentesque vulputate, erat non consequat pretium, ex turpis cursus lectus, eu semper urna felis ut libero. Morbi ut justo posuere, faucibus dolor quis, pulvinar lorem. Sed sagittis mauris sit amet lacus eleifend, at semper felis semper. Mauris rutrum quam eget arcu sodales, a consectetur nisi viverra. Phasellus ante dui, finibus et tincidunt vitae, vestibulum lobortis lorem. Phasellus efficitur elit at nisi elementum cursus. Mauris tellus nisi, sollicitudin vel vestibulum eu, laoreet at nisl.",
];
